// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: storm.proto

package stormhunter

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStreamRequest) Reset() {
	*x = StartStreamRequest{}
	mi := &file_storm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreamRequest) ProtoMessage() {}

func (x *StartStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreamRequest.ProtoReflect.Descriptor instead.
func (*StartStreamRequest) Descriptor() ([]byte, []int) {
	return file_storm_proto_rawDescGZIP(), []int{0}
}

func (x *StartStreamRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *StartStreamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WeatherData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Temp          float32                `protobuf:"fixed32,2,opt,name=temp,proto3" json:"temp,omitempty"`
	Humidity      float32                `protobuf:"fixed32,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Lat           float32                `protobuf:"fixed32,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,5,opt,name=lon,proto3" json:"lon,omitempty"`
	WindKmh       int32                  `protobuf:"varint,6,opt,name=wind_kmh,json=windKmh,proto3" json:"wind_kmh,omitempty"`
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherData) Reset() {
	*x = WeatherData{}
	mi := &file_storm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherData) ProtoMessage() {}

func (x *WeatherData) ProtoReflect() protoreflect.Message {
	mi := &file_storm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherData.ProtoReflect.Descriptor instead.
func (*WeatherData) Descriptor() ([]byte, []int) {
	return file_storm_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherData) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *WeatherData) GetTemp() float32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *WeatherData) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *WeatherData) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *WeatherData) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *WeatherData) GetWindKmh() int32 {
	if x != nil {
		return x.WindKmh
	}
	return 0
}

func (x *WeatherData) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Webcam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StreamUrl     string                 `protobuf:"bytes,3,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"` // HLS URL
	Lat           float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,5,opt,name=lon,proto3" json:"lon,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // "live"/"offline"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Webcam) Reset() {
	*x = Webcam{}
	mi := &file_storm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webcam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webcam) ProtoMessage() {}

func (x *Webcam) ProtoReflect() protoreflect.Message {
	mi := &file_storm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webcam.ProtoReflect.Descriptor instead.
func (*Webcam) Descriptor() ([]byte, []int) {
	return file_storm_proto_rawDescGZIP(), []int{2}
}

func (x *Webcam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Webcam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Webcam) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *Webcam) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Webcam) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Webcam) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetStormWebcamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStormWebcamsRequest) Reset() {
	*x = GetStormWebcamsRequest{}
	mi := &file_storm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStormWebcamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStormWebcamsRequest) ProtoMessage() {}

func (x *GetStormWebcamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStormWebcamsRequest.ProtoReflect.Descriptor instead.
func (*GetStormWebcamsRequest) Descriptor() ([]byte, []int) {
	return file_storm_proto_rawDescGZIP(), []int{3}
}

func (x *GetStormWebcamsRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetStormWebcamsRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetStormWebcamsRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetStormWebcamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webcams       []*Webcam              `protobuf:"bytes,1,rep,name=webcams,proto3" json:"webcams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStormWebcamsResponse) Reset() {
	*x = GetStormWebcamsResponse{}
	mi := &file_storm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStormWebcamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStormWebcamsResponse) ProtoMessage() {}

func (x *GetStormWebcamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStormWebcamsResponse.ProtoReflect.Descriptor instead.
func (*GetStormWebcamsResponse) Descriptor() ([]byte, []int) {
	return file_storm_proto_rawDescGZIP(), []int{4}
}

func (x *GetStormWebcamsResponse) GetWebcams() []*Webcam {
	if x != nil {
		return x.Webcams
	}
	return nil
}

var File_storm_proto protoreflect.FileDescriptor

const file_storm_proto_rawDesc = "" +
	"\n" +
	"\vstorm.proto\x12\vstormhunter\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\x12StartStreamRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xb2\x01\n" +
	"\vWeatherData\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x12\n" +
	"\x04temp\x18\x02 \x01(\x02R\x04temp\x12\x1a\n" +
	"\bhumidity\x18\x03 \x01(\x02R\bhumidity\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x05 \x01(\x02R\x03lon\x12\x19\n" +
	"\bwind_kmh\x18\x06 \x01(\x05R\awindKmh\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\"\x87\x01\n" +
	"\x06Webcam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x03 \x01(\tR\tstreamUrl\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x05 \x01(\x01R\x03lon\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"j\n" +
	"\x16GetStormWebcamsRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"H\n" +
	"\x17GetStormWebcamsResponse\x12-\n" +
	"\awebcams\x18\x01 \x03(\v2\x13.stormhunter.WebcamR\awebcams2\xf5\x01\n" +
	"\fStormService\x12l\n" +
	"\vStartStream\x12\x1f.stormhunter.StartStreamRequest\x1a\x18.stormhunter.WeatherData\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/storm/start/{region}0\x01\x12w\n" +
	"\x0fGetStormWebcams\x12#.stormhunter.GetStormWebcamsRequest\x1a$.stormhunter.GetStormWebcamsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/storm/webcamsB&Z$Storm-Hunt/storm-backend/stormhunterb\x06proto3"

var (
	file_storm_proto_rawDescOnce sync.Once
	file_storm_proto_rawDescData []byte
)

func file_storm_proto_rawDescGZIP() []byte {
	file_storm_proto_rawDescOnce.Do(func() {
		file_storm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storm_proto_rawDesc), len(file_storm_proto_rawDesc)))
	})
	return file_storm_proto_rawDescData
}

var file_storm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_storm_proto_goTypes = []any{
	(*StartStreamRequest)(nil),      // 0: stormhunter.StartStreamRequest
	(*WeatherData)(nil),             // 1: stormhunter.WeatherData
	(*Webcam)(nil),                  // 2: stormhunter.Webcam
	(*GetStormWebcamsRequest)(nil),  // 3: stormhunter.GetStormWebcamsRequest
	(*GetStormWebcamsResponse)(nil), // 4: stormhunter.GetStormWebcamsResponse
}
var file_storm_proto_depIdxs = []int32{
	2, // 0: stormhunter.GetStormWebcamsResponse.webcams:type_name -> stormhunter.Webcam
	0, // 1: stormhunter.StormService.StartStream:input_type -> stormhunter.StartStreamRequest
	3, // 2: stormhunter.StormService.GetStormWebcams:input_type -> stormhunter.GetStormWebcamsRequest
	1, // 3: stormhunter.StormService.StartStream:output_type -> stormhunter.WeatherData
	4, // 4: stormhunter.StormService.GetStormWebcams:output_type -> stormhunter.GetStormWebcamsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_storm_proto_init() }
func file_storm_proto_init() {
	if File_storm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storm_proto_rawDesc), len(file_storm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storm_proto_goTypes,
		DependencyIndexes: file_storm_proto_depIdxs,
		MessageInfos:      file_storm_proto_msgTypes,
	}.Build()
	File_storm_proto = out.File
	file_storm_proto_goTypes = nil
	file_storm_proto_depIdxs = nil
}
