syntax = "proto3";

option go_package = "Storm-Hunt/storm-backend/stormhunter";

package stormhunter;

import "google/api/annotations.proto";

service StormService {
  rpc StartStream(StartStreamRequest) returns (stream WeatherData) {
    option (google.api.http) = {
      get: "/v1/storm/start/{region}"
    };
  }
  rpc GetStormWebcams(GetStormWebcamsRequest) returns (GetStormWebcamsResponse) {
    option (google.api.http) = {
      get: "/v1/storm/webcams"
    };
  }
}

message StartStreamRequest {
  string region = 1;
  string user_id = 2;
}

message WeatherData {
  string region = 1;
  float temp = 2;
  float humidity = 3;
  float lat = 4;
  float lon = 5;
  int32 wind_kmh = 6;
  string timestamp = 7;
}

message Webcam {
  string id = 1;
  string name = 2;
  string stream_url = 3; // HLS URL
  double lat = 4;
  double lon = 5;
  string status = 6; // "live"/"offline"
}

message GetStormWebcamsRequest {
  string region = 1; 
  double latitude = 2; 
  double longitude = 3;
}

message GetStormWebcamsResponse {
  repeated Webcam webcams = 1;
}